spring:
  profiles:
    active: ${PROFILES:local}  # Docker environment variable
    group:
      local: local, common, secret
      blue: blue, common, secret
      green: green, common, secret

server:
  env: ${ENV:local}  # Docker environment variable

---

spring:
  config:
    activate:
      on-profile: local
server:
  port: 8080
  serverAddress: localhost
serverName: local_server

youtube:
  cookies:
    file:
      path: "cookies.txt"

---

spring:
  config:
    activate:
      on-profile: blue
server:
  port: 8080
  serverAddress: 3.36.30.174
serverName: blue_server

# Docker 환경에서 쿠키 파일 경로 설정 (절대 경로)
youtube:
  cookies:
    file:
      path: "/app/config/cookies.txt"

---

spring:
  config:
    activate:
      on-profile: green
server:
  port: 8081
  serverAddress: 3.36.30.174
serverName: green_server

# Docker 환경에서 쿠키 파일 경로 설정 (절대 경로)
youtube:
  cookies:
    file:
      path: "/app/config/cookies.txt"

---

spring:
  config:
    activate:
      on-profile: common
  application:
    name: newsbara

# 임시 디렉토리 설정
app:
  temp:
    dir: "/tmp/youtube-transcripts"  # Docker 환경에서 명시적 경로 설정
